title: idris10x Notes
description: A blog about software and computers
author: idris10x
baseurl: "/blog"
url: "https://idris10x.github.io"

permalink: /:title/

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

collections:
  posts:
    output: true
    permalink: /:title/

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

sass:
  style: compressed

giscus:
  repo: "idris10x/idris10x.github.io"
  repo_id: "R_kgDORm9F3w"
  category: "Announcements"
  category_id: "DIC_kwDORm9F384C5HGr"
  mapping: "pathname"
  reactions_enabled: "1"
  emit_metadata: "0"
  theme: "dark"
  lang: "en"
